version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: ${SQL_SA_PASSWD}
      MSSQL_TELEMETRY_ENABLED: 'FALSE'
    cap_add:
      - SYS_PTRACE
    volumes:
      - sql-data:/var/opt/mssql

  webapi:
    build:
      context: ./XAFApp
      args:
        DXNUGETKEY: ${DXNUGETKEY}
        STARTSCRIPT: '/src/start-webapi.sh'
    depends_on:
      - sql
    environment:
      SQL_DBNAME: XAFDatabase
      SQL_SA_PASSWD: ${SQL_SA_PASSWD}
    ports:
      - '5273:5273'

  blazor:
    build:
      context: ./XAFApp
      args:
        DXNUGETKEY: ${DXNUGETKEY}
        STARTSCRIPT: '/src/start-blazor.sh'
    depends_on:
      - sql
    environment:
      SQL_DBNAME: XAFDatabase
      SQL_SA_PASSWD: ${SQL_SA_PASSWD}
    ports:
      - '5274:5274'

  svelte:
    build: ./svelte-frontend
    depends_on:
      - webapi
    ports:
      - '5173:5173'
    volumes:
      - ./svelte-frontend:/src

volumes:
  sql-data:
